name: sign_in_screen_2
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  intl: ^0.17.0
  path_provider: ^2.0.9
  shared_preferences: ^2.0.13

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - lib/assets/images/product-placeholder.jpg

  fonts:
    - family: Lato
      fonts:
        - asset: lib/assets/fonts/Lato-Regular.ttf
        - asset: lib/assets/fonts/Lato-Bold.ttf
          weight: 700

    - family: Anton
      fonts:
        - asset: lib/assets/fonts/Anton-Regular.ttf
